### ISSUE TITLE
Member/user dash

### ISSUE THREAD

**Issue by cristiansc** [adventistmedia/adventisthub-support#81]
In dash, for 'coming up', not showing anything - can this show any/all upcoming visits/tasks?
e.g. for Mike Smith, I have an active contact - this should auto generate a 'coming up' visit within the next 7 days.
I have also created a 'todo' activity 12 days away - this should show on the dash too

**Comment by danlewis** [comment]
The coming up section will show all activities which are todo's created in the current team and the activity is assigned to me (you can actually create an activity and assign that activity to one of the other people assigned to the contact).

However if the activity was created by another team (e.g. a HQ team) the activities don't currently show. This needs some thought on my part

**Comment by cristiansc** [comment]
I created a 'todo' by Mike Smith for Mike Smith - but still not showing up in Mike's dash - is that the bug?

**Comment by danlewis** [comment]
All unassigned activities belong to a contact are now auto assigned to the new user assigned to the contact.
This should now work for all future activities

**Comment by cristiansc** [comment]
Just tried this - added a new 'todo' visit for Johnny Citizened in team Sample for user Cristian.
But activity still doesn't show in dash

**Comment by danlewis** [comment]
This appears to have been a caching issue on production. This has now been resolved
